In [ ]:
import numpy as np
import os
import  matplotlib.image as mpimg
from scipy import misc
from PIL import Image
import matplotlib.pyplot as plt

In [ ]:
def img_to_vector(filename):
    img  = Image.open(filename).resize((112, 92)) 
    img_vector = np.array(img).flatten()
    sz = img_vector.shape[0]
    return img_vector

In [ ]:
def preprocess(dataset_dir = "/home/Abhishek/Desktop/Soft computing/faces"):
    train_set = []
    train_set_number = []
    test_set = []
    test_set_number = []
    for i in range(40):
        person_id = i+1
        for j in range(10):
            if j < 6 :
                path = dataset_dir + '/s'+str(person_id)+'/'+str(j+1)+'.jpg'
                img = img_to_vector(path).astype(np.int64) 
                train_set.append(img)
                train_set_number.append(person_id)
            else : 
                path = dataset_dir + '/s'+str(person_id)+'/'+str(j+1)+'.jpg'
                img = img_to_vector(path).astype(np.int64)
                test_set.append(img)
                test_set_number.append(person_id)
        
    train_set = np.array(train_set)
    train_set_number = np.array(train_set_number)
    test_set = np.array(test_set)
    test_set_number = np.array(test_set_number)
    return train_set.T, train_set_number, test_set.T, test_set_number

In [ ]:
train_set,train_set_number,test_set,test_set_number = preprocess()

In [ ]:
print(train_set)
print(train_set.shape)

[[ 48  60  39 ... 130 128 123]
 [ 48  60  39 ... 130 128 123]
 [ 49  60  44 ... 123 125 121]
 ...
 [ 46  36  30 ...  38  86  35]
 [ 47  36  29 ...  32  88  45]
 [ 47  31  27 ...  42  91  39]]
(10304, 240)


In [ ]:
print(train_set_number)
print(train_set_number.shape)

[ 1  1  1  1  1  1  2  2  2  2  2  2  3  3  3  3  3  3  4  4  4  4  4  4
  5  5  5  5  5  5  6  6  6  6  6  6  7  7  7  7  7  7  8  8  8  8  8  8
  9  9  9  9  9  9 10 10 10 10 10 10 11 11 11 11 11 11 12 12 12 12 12 12
 13 13 13 13 13 13 14 14 14 14 14 14 15 15 15 15 15 15 16 16 16 16 16 16
 17 17 17 17 17 17 18 18 18 18 18 18 19 19 19 19 19 19 20 20 20 20 20 20
 21 21 21 21 21 21 22 22 22 22 22 22 23 23 23 23 23 23 24 24 24 24 24 24
 25 25 25 25 25 25 26 26 26 26 26 26 27 27 27 27 27 27 28 28 28 28 28 28
 29 29 29 29 29 29 30 30 30 30 30 30 31 31 31 31 31 31 32 32 32 32 32 32
 33 33 33 33 33 33 34 34 34 34 34 34 35 35 35 35 35 35 36 36 36 36 36 36
 37 37 37 37 37 37 38 38 38 38 38 38 39 39 39 39 39 39 40 40 40 40 40 40]
(240,)


In [ ]:
print(test_set)
print(test_set.shape)

[[ 41  44  42 ... 125 119 125]
 [ 41  44  42 ... 125 119 125]
 [ 47  43  41 ... 119 120 124]
 ...
 [ 37  44  44 ...  40  93  32]
 [ 39  36  42 ...  39  90  35]
 [ 33  32  39 ...  35  92  32]]
(10304, 160)


In [ ]:
print(test_set_number)
print(test_set_number.shape)

[ 1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  5  5  5  5  6  6  6  6
  7  7  7  7  8  8  8  8  9  9  9  9 10 10 10 10 11 11 11 11 12 12 12 12
 13 13 13 13 14 14 14 14 15 15 15 15 16 16 16 16 17 17 17 17 18 18 18 18
 19 19 19 19 20 20 20 20 21 21 21 21 22 22 22 22 23 23 23 23 24 24 24 24
 25 25 25 25 26 26 26 26 27 27 27 27 28 28 28 28 29 29 29 29 30 30 30 30
 31 31 31 31 32 32 32 32 33 33 33 33 34 34 34 34 35 35 35 35 36 36 36 36
 37 37 37 37 38 38 38 38 39 39 39 39 40 40 40 40]
(160,)


In [ ]:
def find_mean(arr):
    M = np.mean(arr, axis = 1)
    return M

In [ ]:
M = find_mean(train_set)
print(M)

[84.82916667 84.82916667 84.82916667 ... 71.36666667 70.98333333
 71.25833333]


In [ ]:
def mean_normalization(arr):
    M = find_mean(arr)
    x_range = arr.shape[0]
    y_range = arr.shape[1]
    for i in range(x_range):
        for j in range(y_range):
            arr[i][j] -= M[i]
    return arr 

In [ ]:
A = mean_normalization(train_set)
A = A
print(A)

[[-36 -24 -45 ...  45  43  38]
 [-36 -24 -45 ...  45  43  38]
 [-35 -24 -40 ...  38  40  36]
 ...
 [-25 -35 -41 ... -33  14 -36]
 [-23 -34 -41 ... -38  17 -25]
 [-24 -40 -44 ... -29  19 -32]]


In [ ]:
print(A.shape)

(10304, 240)


In [ ]:
L = np.dot(A.T, A)
print(L.shape)
print(L)

(240, 240)
[[14138215  6515331  9440618 ... -2067375  1860167   323956]
 [ 6515331 25842748 10578511 ...  3354289  3287386  3280402]
 [ 9440618 10578511 19326264 ...  1590281  2590912  2832988]
 ...
 [-2067375  3354289  1590281 ... 13889491  3270886  4768320]
 [ 1860167  3287386  2590912 ...  3270886 10443756  3900750]
 [  323956  3280402  2832988 ...  4768320  3900750 12427889]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(L)
print("eigenvalues shape : ", eigenvalues.shape)
print("eigenvalues : ", eigenvalues)
print("eigenvectors shape : ", eigenvectors.shape)
print("eigenvectors : ", eigenvectors)

eigenvalues shape :  (240,)
eigenvalues :  [6.95968873e+08 4.87058906e+08 2.73928440e+08 2.08194838e+08
 1.91082827e+08 1.25980285e+08 1.00480476e+08 9.45152745e+07
 7.38933965e+07 7.07004624e+07 5.89995842e+07 5.11042294e+07
 4.38628424e+07 4.34130164e+07 3.89540164e+07 3.77925967e+07
 3.62968084e+07 3.32231132e+07 3.20385733e+07 2.83935136e+07
 2.76394518e+07 2.53170866e+07 2.37959117e+07 2.20956368e+07
 2.17589853e+07 2.04297537e+07 2.02961604e+07 1.95020444e+07
 1.88536797e+07 1.77550975e+07 1.73076957e+07 1.63995599e+07
 1.60236256e+07 1.55658373e+07 1.54560047e+07 1.48426469e+07
 1.37821406e+07 1.33848362e+07 1.32198534e+07 1.27661796e+07
 1.23507519e+07 1.22196475e+07 1.18924320e+07 1.15385019e+07
 1.11289130e+07 1.08710279e+07 1.04758472e+07 9.96438719e+06
 9.85058123e+06 9.61997204e+06 9.41188500e+06 9.36627859e+06
 9.02370035e+06 8.84972407e+06 8.58983676e+06 8.43890256e+06
 8.15341563e+06 8.06442729e+06 7.74318573e+06 7.58327863e+06
 7.55250463e+06 7.41907586e+06 7.17991368e

In [ ]:
U = []
sz = L.shape[0]
for i in range(sz):
    U.append(np.dot(A,eigenvectors[:,i]))

U = np.array(U)
U = U.T
print(U.shape)
print(U)

(10304, 240)
[[ 107.36107408 -324.65948848 -322.92099856 ...   -4.84683181
     7.73683409   -5.74773245]
 [ 107.36107408 -324.65948848 -322.92099856 ...   -4.84683181
     7.73683409   -5.74773245]
 [ 106.9362837  -327.55853219 -322.33678109 ...   -3.17191828
    12.20103856   -8.03736982]
 ...
 [ 156.51790565  211.79398684 -186.06759496 ...  -25.51923804
     3.06072344  -12.4666604 ]
 [ 157.05808021  204.21515252 -202.80332625 ...  -23.85186024
    14.61984345    8.97158879]
 [ 151.89863949  179.31370562 -208.55534691 ...  -28.54484279
    16.84016349   -3.23985459]]


In [ ]:
weight_vector = np.dot(U.T, A)
print(weight_vector.shape)
print(weight_vector)

(240, 240)
[[-3.57026341e+07 -7.65273900e+07 -6.77621720e+07 ... -1.28518977e+07
  -2.47063430e+07 -1.10606267e+07]
 [-2.77421537e+07 -2.42775587e+07 -1.59605755e+07 ... -6.33435973e+06
  -4.02614961e+07 -2.81443573e+07]
 [ 3.06780828e+07 -5.66986370e+06  1.49141122e+07 ... -3.78550772e+07
  -1.46222962e+07 -2.68448891e+07]
 ...
 [ 4.44710345e+04  6.87445784e+04 -1.11166493e+05 ... -1.12432243e+04
   4.49983250e+04  1.59509393e+05]
 [-3.77462979e+04 -9.39057389e+04 -1.29265113e+05 ... -4.65256163e+03
   5.16443628e+04  4.22564683e+04]
 [-6.19722078e+03  3.46847953e+04 -7.12788347e+03 ...  4.49975047e+04
  -9.62795394e+04 -8.86670351e+04]]


In [ ]:
overall_mean = np.mean(weight_vector, axis = 1)
overall_mean = overall_mean.reshape(overall_mean.shape[0],1)
print(overall_mean.shape)

(240, 1)


In [ ]:
SW = np.zeros([240,240])
for i in range(40):
    ind = i * 6
    V = weight_vector[:,ind:ind+6]
    mean_local = np.mean(V, axis = 1)
    mean_local = mean_local.reshape(mean_local.shape[0],1)
    mean = np.repeat(mean_local, 6,axis = 1)
    diff = V - mean
    variance = np.dot(diff, diff.T)
    SW = SW + variance

In [ ]:
SB = np.zeros([240,240])
print(variance.shape)
for i in range(40):
    j = i+6
    V = weight_vector[:,i:j]
    mean_local = np.mean(V, axis = 1)
    mean_local = mean_local.reshape(mean_local.shape[0],1)
    diff = mean_local - overall_mean
    sigma = np.dot(diff, mean_local.T)
    SB = SB  + sigma

(240, 240)


In [ ]:
J = np.dot(np.linalg.pinv(SW), SB)
print(J.shape)

(240, 240)


In [ ]:
eigenval, eigenvec = np.linalg.eig(J)
fisher_faces = np.dot(eigenvec.T, weight_vector)
print(fisher_faces.shape)

(240, 240)


# Testing


In [ ]:
x_range = test_set.shape[0]
y_range = test_set.shape[1]
print(M)
print(test_set)
for i in range(x_range):
    for j in range(y_range):
        test_set[i][j] -= M[i]
print(test_set.shape)
print(test_set)

[84.82916667 84.82916667 84.82916667 ... 71.36666667 70.98333333
 71.25833333]
[[ 41  44  42 ... 125 119 125]
 [ 41  44  42 ... 125 119 125]
 [ 47  43  41 ... 119 120 124]
 ...
 [ 37  44  44 ...  40  93  32]
 [ 39  36  42 ...  39  90  35]
 [ 33  32  39 ...  35  92  32]]
(10304, 160)
[[-43 -40 -42 ...  40  34  40]
 [-43 -40 -42 ...  40  34  40]
 [-37 -41 -43 ...  34  35  39]
 ...
 [-34 -27 -27 ... -31  21 -39]
 [-31 -34 -28 ... -31  19 -35]
 [-38 -39 -32 ... -36  20 -39]]


In [ ]:
weight_vector_test = np.dot(U.T, test_set)
print(weight_vector_test.shape)
print(weight_vector_test)

(240, 160)
[[-5.84235270e+07 -6.98262822e+07 -6.69859631e+07 ... -1.56717498e+07
  -3.06895091e+07 -9.88783795e+06]
 [-2.03676688e+07 -1.44840975e+07 -2.93871957e+07 ... -2.70429673e+07
  -3.20439800e+07 -1.48825896e+07]
 [ 2.06941178e+07  2.10793613e+07  1.23532452e+07 ... -2.56061602e+07
  -1.01073327e+07 -3.58169846e+07]
 ...
 [-1.69347510e+04 -7.75741379e+04 -6.03774466e+04 ...  1.42327733e+05
  -1.20430459e+05  2.06675366e+05]
 [-5.49623319e+04 -2.57225302e+04 -8.22383856e+04 ... -5.35726173e+04
   5.85360195e+03  9.58496498e+04]
 [ 3.59779058e+04  6.66562223e+04  2.15996853e+05 ...  4.25854284e+02
  -4.17520541e+04  7.14431706e+04]]


In [ ]:
projected_fisher_faces = np.dot(eigenvec.T, weight_vector_test)
print(projected_fisher_faces.shape)

(240, 160)


In [ ]:
validation = []
count = 0
for i in range(160) : 
    ith_wv = projected_fisher_faces[:,i]
    ans = 0
    index = 0
    for j in range(240):
        jth_wv = fisher_faces[:,j]
        diff = ith_wv - jth_wv
        diff = np.absolute(diff)
        sm = np.sum(diff)
        if ans == 0 :
            ans = sm
            index = j
        else :
            if sm < ans:
                ans = sm
                index = j
    print(train_set_number[index])
    if train_set_number[index] == test_set_number[i]:
        count = count + 1
        validation.append(1)
    else:
        validation.append(0)

1
1
1
1
2
2
2
2
3
3
3
3
4
4
4
4
5
5
5
5
6
6
6
6
7
7
7
7
8
8
8
8
9
9
9
9
10
10
23
8
4
38
3
11
12
12
3
12
5
5
13
13
4
4
14
4
15
15
15
15
1
1
1
16
17
17
17
17
18
18
18
18
19
5
8
19
20
29
40
20
21
21
21
21
22
22
22
22
23
23
23
23
24
24
24
24
25
25
25
25
3
26
26
26
4
27
27
27
28
3
4
8
29
29
29
29
30
30
30
30
25
31
31
31
3
5
32
32
33
38
33
33
34
34
34
34
35
35
35
35
36
36
5
3
3
8
37
37
38
38
38
38
30
39
39
30
40
40
13
5


In [ ]:
print(validation)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0]


In [ ]:
print("accuracy = ", (count*100)/160, "%")

accuracy =  78.125 %
