In [ ]:
import pandas as pd
import numpy as np
import math
from scipy.spatial import distance

In [ ]:
data = pd.read_excel('/content/Absenteeism_at_work.xls')

In [ ]:
data=data.values

In [ ]:
def seed_selection(n):
    k=[0]*n
    seed=np.random.randint(data.shape[0], size=1)
    for i in range(n):
        if i==0:
            k[0]=math.floor(seed)
        elif (i==1):
            k[1]=math.floor(k[0]/2)
        else:
            k[i]=math.floor(sum(k)/len(k))
    return(k)

In [ ]:
#initial centroids
k=seed_selection(2)
k

[231, 115]

In [ ]:
dist_mat = np.zeros((len(k),740))

In [ ]:
def eclid_distance(centroid):
    for i in range(len(centroid)):
        for j in range(data.shape[0]):
              dist_mat[i][j] =np.sqrt(np.sum(np.square(centroid[i]-data[j:j+1,])))       
    return(dist_mat)

In [ ]:
def kmean(k):
    centroid=[]
    for i in range(len(k)):
        centroid.append(data[k[i]])
    dist_mat=eclid_distance(centroid)
    for i in range(21):
        x = [[] for _ in range(len(k))]
        for i in range(data.shape[0]):
            for j in range(len(k)):
                if (dist_mat[:,i])[j]==dist_mat[:,i].min():
                    x[j].append(data[i])
        for i in range(len(k)):
            x[i]=np.array(x[i])
            centroid[i]=x[i].mean(axis=0)
    return x,centroid

In [ ]:
cls,centroid = kmean(k)

In [ ]:
# clusters with their data items
cls

[array([[ 19,  28,   3, ..., 169,  23,   2],
        [ 20,  19,   3, ..., 168,  23,   8],
        [ 30,  19,   3, ..., 185,  22,   3],
        ...,
        [  3,  11,   6, ..., 170,  31,   2],
        [ 32,  28,   6, ..., 172,  36,   2],
        [ 28,  28,   6, ..., 169,  24,   2]]),
 array([[ 11,  26,   7, ..., 172,  30,   4],
        [ 36,   0,   7, ..., 178,  31,   0],
        [  3,  23,   7, ..., 170,  31,   2],
        ...,
        [  4,   0,   0, ..., 170,  34,   0],
        [  8,   0,   0, ..., 170,  35,   0],
        [ 35,   0,   0, ..., 175,  25,   0]])]

In [ ]:
len(cls[0][0])

21

In [ ]:
#final centroids
centroid

[array([1.91147541e+01, 1.57049180e+01, 4.31147541e+00, 3.75409836e+00,
        2.60655738e+00, 2.29393443e+02, 2.99836066e+01, 1.30000000e+01,
        3.63278689e+01, 3.61594770e+05, 9.39508197e+01, 6.55737705e-02,
        1.16393443e+00, 1.24590164e+00, 6.22950820e-01, 1.47540984e-01,
        7.21311475e-01, 7.76393443e+01, 1.73442623e+02, 2.57377049e+01,
        9.22950820e+00]),
 array([1.79189985e+01, 1.95316642e+01, 6.50515464e+00, 3.92930781e+00,
        2.53902798e+00, 2.20605302e+02, 2.95994109e+01, 1.25139912e+01,
        3.64609720e+01, 2.63395424e+05, 9.46450663e+01, 5.30191458e-02,
        1.30338733e+00, 9.98527246e-01, 5.62592047e-01, 6.62739323e-02,
        7.48159057e-01, 7.91605302e+01, 1.71995582e+02, 2.67614138e+01,
        6.71723122e+00])]

In [ ]:
cls[0][0]

array([    19,     28,      3,      3,      2,    291,     50,     12,
           32, 343253,     95,      0,      1,      0,      1,      0,
            0,     65,    169,     23,      2])

In [ ]:
# error for first cluster
sse_1 = 0
for i in range(len(cls[0])):
    sse_1 = sse_1 + np.square(distance.euclidean(centroid[0],cls[0][i]))

In [ ]:
sse_1

18612312631.836063

In [ ]:
# error for second cluster
sse_2 = 0
for i in range(len(cls[1])):
    sse_2 = sse_2 + np.square(distance.euclidean(centroid[1],cls[1][i]))

In [ ]:
sse_2

569022497334.7479

In [ ]:
#final error
sse = sse_1 + sse_2
sse

587634809966.584

In [ ]:

from sklearn.cluster import KMeans
import numpy as np

kmeans = KMeans(n_clusters=2, random_state=0).fit(data)
#

kmeans.cluster_centers_


array([[1.76805054e+01, 1.93880866e+01, 7.00722022e+00, 3.90613718e+00,
        2.56137184e+00, 2.22146209e+02, 2.99512635e+01, 1.25108303e+01,
        3.65902527e+01, 2.52753984e+05, 9.48176895e+01, 5.59566787e-02,
        1.32490975e+00, 1.00180505e+00, 5.75812274e-01, 6.67870036e-02,
        7.74368231e-01, 7.93122744e+01, 1.71873646e+02, 2.68574007e+01,
        6.74007220e+00],
       [1.90215054e+01, 1.87043011e+01, 4.29032258e+00, 3.94086022e+00,
        2.49462366e+00, 2.18897849e+02, 2.86774194e+01, 1.26827957e+01,
        3.60322581e+01, 3.27296059e+05, 9.39032258e+01, 4.83870968e-02,
        1.19354839e+00, 1.06989247e+00, 5.43010753e-01, 9.13978495e-02,
        6.61290323e-01, 7.82096774e+01, 1.72833333e+02, 2.61397849e+01,
        7.47311828e+00]])

In [ ]:
#sum of errors
kmeans.inertia_

353637366625.63495