In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/ionosphere.data', header = None)
#df.head()

In [ ]:
y = df.iloc[:,-1].replace(to_replace=['g', 'b'], value=[-1, 1])
x = df.iloc[:,0:-1]
#print(df.head())
#print(x.head())
#print(y.head())

In [ ]:
x = (x - x.mean())/ (x.max() - x.min())
x = pd.DataFrame(x)
x.insert(0, 'x0', 1, True)
x.head()

x0         0   1         2  ...        30        31        32        33
0   1  0.108262 NaN  0.177024  ...  0.035078 -0.270538 -0.081477 -0.233740
1   1  0.108262 NaN  0.179329  ... -0.259387 -0.029543 -0.243372 -0.019475
2   1  0.108262 NaN  0.179329  ...  0.125923 -0.119003  0.105543 -0.198430
3   1  0.108262 NaN  0.179329  ... -0.047847  0.501897 -0.336592  0.492760
4   1  0.108262 NaN  0.179329  ... -0.204792 -0.295968 -0.197722 -0.335725

[5 rows x 35 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.65)
print(x_train.head())
print(y_train.head())
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

     x0         0   1         2  ...        30        31        32        33
296   1  0.108262 NaN  0.119909  ... -0.328817 -0.331603 -0.271242 -0.385225
82    1  0.108262 NaN  0.140714  ... -0.162582  0.387257 -0.194797  0.340305
86    1  0.108262 NaN  0.017064  ...  0.255818  0.020767  0.191358 -0.003465
14    1  0.108262 NaN  0.179329  ...  0.323743  0.164357  0.325318  0.226320
252   1  0.108262 NaN -0.320671  ... -0.176257  0.001897 -0.174682 -0.007240

[5 rows x 35 columns]
296   -1
82    -1
86    -1
14    -1
252    1
Name: 34, dtype: int64


In [ ]:
def svm(x_train, y_train, x_test, y_test, epochs, alpha):
    m, n = x_train.shape
    w = np.zeros(n)
    costs = []
    
    for i in range(epochs):
        y_pred = np.dot(x_train, w)
        cost = 0
        prod = y_train * y_pred
        for j in range(prod.shape[0]):
            val = prod[j]
            if(val >= 1):
            
                w = w - alpha * (2 * 1/epochs * w)
            else:
                cost = cost + 1 - val 
                w = w + alpha * (x_train[j].T * y_train[j]  - 2 * 1/epochs * w)  
            
            costs.append(cost)
    return w, costs

In [ ]:
w, costs= svm(x_train, y_train, x_test, y_test, 500, 5e-4)

In [ ]:
def pred(X):
    y = (np.dot(w, X))
    return y.T

In [ ]:
y_pred = np.dot(x_test, w)
predictions = []
for val in y_pred:
    if(val >= 1):
        predictions.append(1)
    else:
        predictions.append(-1)
predictions = np.array(predictions)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions))

0.6585365853658537


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(predictions, y_test)
cm

array([[81, 42],
       [ 0,  0]])

In [ ]:
tp=cm[0][0]
fn=cm[1][0]
fp=cm[0][1]
tn=cm[1][1]

accuracy = (tp+tn)/np.sum(cm)
precision=tp/(tp+tn)
recall=tp/(tp+fn)
f_score=2*recall*precision/(recall+precision)

print("Accuracy : ",accuracy)
print("Precision : ",precision)
print("Recall : ",recall)
print("F_score : ",f_score)

Accuracy :  0.6585365853658537
Precision :  1.0
Recall :  1.0
F_score :  1.0


## as our data is linearly inseperable we will use kernel trick for better accuracy

In [ ]:
y = df.iloc[:,-1].replace(to_replace=['g', 'b'], value=[-1, 1])
x = df.iloc[:,0:-1]
print(df.head())
print(x.head())
print(y.head())

   0   1        2        3        4   ...       30       31       32       33  34
0   1   0  0.99539 -0.05889  0.85243  ...  0.42267 -0.54487  0.18641 -0.45300   g
1   1   0  1.00000 -0.18829  0.93035  ... -0.16626 -0.06288 -0.13738 -0.02447   b
2   1   0  1.00000 -0.03365  1.00000  ...  0.60436 -0.24180  0.56045 -0.38238   g
3   1   0  1.00000 -0.45161  1.00000  ...  0.25682  1.00000 -0.32382  1.00000   b
4   1   0  1.00000 -0.02401  0.94140  ... -0.05707 -0.59573 -0.04608 -0.65697   g

[5 rows x 35 columns]
   0   1        2        3   ...       30       31       32       33
0   1   0  0.99539 -0.05889  ...  0.42267 -0.54487  0.18641 -0.45300
1   1   0  1.00000 -0.18829  ... -0.16626 -0.06288 -0.13738 -0.02447
2   1   0  1.00000 -0.03365  ...  0.60436 -0.24180  0.56045 -0.38238
3   1   0  1.00000 -0.45161  ...  0.25682  1.00000 -0.32382  1.00000
4   1   0  1.00000 -0.02401  ... -0.05707 -0.59573 -0.04608 -0.65697

[5 rows x 34 columns]
0   -1
1    1
2   -1
3    1
4   -1
Name: 34, dty

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.70)

print(x_train.head())

print(y_train.head())

x_train = np.array(x_train)

y_train = np.array(y_train)

x_test = np.array(x_test)

y_test = np.array(y_test)

     0   1        2        3   ...       30       31       32       33
332   1   0  0.87578  0.03727  ...  0.80757  0.02308  0.80088  0.02441
78    1   0  1.00000  0.24168  ... -0.17370  1.00000 -0.81383  1.00000
22    1   0  0.96071  0.07088  ...  0.51310 -0.00015  0.52099 -0.00182
119   1   0  0.86889 -0.07111  ...  1.00000 -0.15609  1.00000 -0.44222
345   1   0  0.66667 -0.01366  ...  0.55328  0.24590  0.13934  0.48087

[5 rows x 34 columns]
332   -1
78    -1
22    -1
119   -1
345   -1
Name: 34, dtype: int64


In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train, y_train)

y_pred =[]
y_pred = svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[65  1]
 [ 8 32]]
              precision    recall  f1-score   support

          -1       0.89      0.98      0.94        66
           1       0.97      0.80      0.88        40

    accuracy                           0.92       106
   macro avg       0.93      0.89      0.91       106
weighted avg       0.92      0.92      0.91       106



In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

y_pred = []
y_pred = svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[60  6]
 [14 26]]
              precision    recall  f1-score   support

          -1       0.81      0.91      0.86        66
           1       0.81      0.65      0.72        40

    accuracy                           0.81       106
   macro avg       0.81      0.78      0.79       106
weighted avg       0.81      0.81      0.81       106



In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)

y_pred = []
y_pred = svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[66  0]
 [ 4 36]]
              precision    recall  f1-score   support

          -1       0.94      1.00      0.97        66
           1       1.00      0.90      0.95        40

    accuracy                           0.96       106
   macro avg       0.97      0.95      0.96       106
weighted avg       0.96      0.96      0.96       106

